import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./(routes)/(components)/sidebar";
import { NavMenu } from "./(routes)/(components)/nav-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex gap-x-20 w-full overflow-hidden">
        <div className="sr-only md:not-sr-only">
          <SideBar />
        </div>
        <div className="w-full h-screen">
            <NavMenu />
            {children}
        </div>
      </div>
      </body>
    </html>
  );
}
